repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    -   id: end-of-file-fixer
        files: CMakeLists.txt|configure.ac|Makefile.am|\.xml$|\.yml$
        exclude: src/IPhreeqcPhast/IPhreeqc/phreeqcpp/test.xml$|Doxygen/DoxygenLayout.xml$
    -   id: trailing-whitespace
        files: CMakeLists.txt|configure.ac|Makefile.am|\.xml$|\.yml$
        exclude: src/IPhreeqcPhast/IPhreeqc/phreeqcpp/test.xml$|Doxygen/DoxygenLayout.xml$
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, develop]
