#!/bin/sh
export INTERFACE_F90=../src/BMI_interface.F90 
export YAML_INTERFACE_F90=../src/YAML_interface.F90
# sed -i -e "s/PhreeqcRM/phreeqcrm/g" $INTERFACE_F90
sed -i -e "s/RM_/rm_/g" 
sed -i -e "s/GetGridCellCountYAML/getgridcellcountyaml/g" $INTERFACE_F90
sed -i -e "s/SetGridCellCountYAML/setgridcellcountyaml/g" $INTERFACE_F90
sed -i -e "s/Abort/abort/g" $INTERFACE_F90
sed -i -e "s/CloseFiles/closefiles/g" $INTERFACE_F90
sed -i -e "s/Concentrations2Utility/concentrations2utility/g" $INTERFACE_F90
sed -i -e "s/CreateMapping/createmapping/g" $INTERFACE_F90
sed -i -e "s/Create/create/g" $INTERFACE_F90
sed -i -e "s/DecodeError/decodeerror/g" $INTERFACE_F90
sed -i -e "s/Destroy/destroy/g" $INTERFACE_F90
sed -i -e "s/DumpModule/dumpmodule/g" $INTERFACE_F90
sed -i -e "s/ErrorMessage/errormessage/g" $INTERFACE_F90
sed -i -e "s/FindComponents/findcomponents/g" $INTERFACE_F90
sed -i -e "s/GetBackwardMapping/getbackwardmapping/g" $INTERFACE_F90
sed -i -e "s/GetChemistryCellCount/getchemistrycellcount/g" $INTERFACE_F90
sed -i -e "s/GetComponentCount/getcomponentcount/g" $INTERFACE_F90
sed -i -e "s/GetComponent/getcomponent/g" $INTERFACE_F90
sed -i -e "s/GetConcentrations/getconcentrations/g" $INTERFACE_F90
sed -i -e "s/GetCurrentSelectedOutputUserNumber/getcurrentselectedoutputusernumber/g" $INTERFACE_F90
sed -i -e "s/GetDensityCalculated/getdensitycalculated/g" $INTERFACE_F90
sed -i -e "s/GetDensity/getdensity/g" $INTERFACE_F90
sed -i -e "s/GetEndCell/getendcell/g" $INTERFACE_F90
sed -i -e "s/GetErrorString/geterrorstring/g" $INTERFACE_F90
sed -i -e "s/GetErrorStringLength/geterrorstringlength/g" $INTERFACE_F90
sed -i -e "s/GetFilePrefix/getfileprefix/g" $INTERFACE_F90
sed -i -e "s/GetGasCompMoles/getgascompmoles/g" $INTERFACE_F90
sed -i -e "s/GetGasCompPhi/getgascompphi/g" $INTERFACE_F90
sed -i -e "s/GetGasCompPressures/getgascomppressures/g" $INTERFACE_F90
sed -i -e "s/GetGasPhaseVolume/getgasphasevolume/g" $INTERFACE_F90
sed -i -e "s/GetGfw/getgfw/g" $INTERFACE_F90
sed -i -e "s/GetGridCellCount/getgridcellcount/g" $INTERFACE_F90
sed -i -e "s/GetIPhreeqcId/getiphreeqcid/g" $INTERFACE_F90
sed -i -e "s/GetMpiMyself/getmpimyself/g" $INTERFACE_F90
sed -i -e "s/GetMpiTasks/getmpitasks/g" $INTERFACE_F90
sed -i -e "s/GetNthSelectedOutputUserNumber/getnthselectedoutputusernumber/g" $INTERFACE_F90
sed -i -e "s/GetPorosity/getporosity/g" $INTERFACE_F90
sed -i -e "s/GetPressure/getpressure/g" $INTERFACE_F90
sed -i -e "s/GetSaturationCalculated/getsaturationcalculated/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutputColumnCount/getselectedoutputcolumncount/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutputCount/getselectedoutputcount/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutputHeading/getselectedoutputheading/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutputRowCount/getselectedoutputrowcount/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutput/getselectedoutput/g" $INTERFACE_F90
sed -i -e "s/GetSolutionVolume/getsolutionvolume/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesConcentrations/getspeciesconcentrations/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesCount/getspeciescount/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesD25/getspeciesd25/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesLog10Molalities/getspecieslog10molalities/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesName/getspeciesname/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesSaveOn/getspeciessaveon/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesZ/getspeciesz/g" $INTERFACE_F90
sed -i -e "s/GetStartCell/getstartcell/g" $INTERFACE_F90
sed -i -e "s/GetThreadCount/getthreadcount/g" $INTERFACE_F90
sed -i -e "s/GetTimeConversion/gettimeconversion/g" $INTERFACE_F90
sed -i -e "s/GetTimeStep/gettimestep/g" $INTERFACE_F90
sed -i -e "s/GetTime/gettime/g" $INTERFACE_F90
sed -i -e "s/InitializeYAML/initializeyaml/g" $INTERFACE_F90
sed -i -e "s/InitialPhreeqc2Concentrations/initialphreeqc2concentrations/g" $INTERFACE_F90
sed -i -e "s/InitialPhreeqc2Module/initialphreeqc2module/g" $INTERFACE_F90
sed -i -e "s/InitialPhreeqcCell2Module/initialphreeqccell2module/g" $INTERFACE_F90
sed -i -e "s/InitialPhreeqc2SpeciesConcentrations/initialphreeqc2speciesconcentrations/g" $INTERFACE_F90
sed -i -e "s/LoadDatabase/loaddatabase/g" $INTERFACE_F90
sed -i -e "s/LogMessage/logmessage/g" $INTERFACE_F90
sed -i -e "s/MpiWorkerBreak/mpiworkerbreak/g" $INTERFACE_F90
sed -i -e "s/MpiWorker/mpiworker/g" $INTERFACE_F90
sed -i -e "s/OpenFiles/openfiles/g" $INTERFACE_F90
sed -i -e "s/OutputMessage/outputmessage/g" $INTERFACE_F90
sed -i -e "s/RunCells/runcells/g" $INTERFACE_F90
sed -i -e "s/RunFile/runfile/g" $INTERFACE_F90
sed -i -e "s/RunString/runstring/g" $INTERFACE_F90
sed -i -e "s/ScreenMessage/screenmessage/g" $INTERFACE_F90
sed -i -e "s/SetComponentH2O/setcomponenth2o/g" $INTERFACE_F90
sed -i -e "s/SetConcentrations/setconcentrations/g" $INTERFACE_F90
sed -i -e "s/SetCurrentSelectedOutputUserNumber/setcurrentselectedoutputusernumber/g" $INTERFACE_F90
sed -i -e "s/SetDensityUser/setdensityuser/g" $INTERFACE_F90
sed -i -e "s/SetDumpFileName/setdumpfilename/g" $INTERFACE_F90
sed -i -e "s/SetErrorHandlerMode/seterrorhandlermode/g" $INTERFACE_F90
sed -i -e "s/SetErrorOn/seterroron/g" $INTERFACE_F90
sed -i -e "s/SetFilePrefix/setfileprefix/g" $INTERFACE_F90
sed -i -e "s/SetGasCompMoles/setgascompmoles/g" $INTERFACE_F90
sed -i -e "s/SetGasPhaseVolume/setgasphasevolume/g" $INTERFACE_F90
sed -i -e "s/SetMpiWorkerCallback/setmpiworkercallback/g" $INTERFACE_F90
sed -i -e "s/SetNthSelectedOutput/setnthselectedoutput/g" $INTERFACE_F90
sed -i -e "s/SetPartitionUZSolids/setpartitionuzsolids/g" $INTERFACE_F90
sed -i -e "s/SetPorosity/setporosity/g" $INTERFACE_F90
sed -i -e "s/SetPrintChemistryMask/setprintchemistrymask/g" $INTERFACE_F90
sed -i -e "s/SetPrintChemistryOn/setprintchemistryon/g" $INTERFACE_F90
sed -i -e "s/SetPressure/setpressure/g" $INTERFACE_F90
sed -i -e "s/SetRebalanceFraction/setrebalancefraction/g" $INTERFACE_F90
sed -i -e "s/SetRebalanceByCell/setrebalancebycell/g" $INTERFACE_F90
sed -i -e "s/SetRepresentativeVolume/setrepresentativevolume/g" $INTERFACE_F90
sed -i -e "s/SetSaturationUser/setsaturationuser/g" $INTERFACE_F90
sed -i -e "s/SetSaturation/setsaturation/g" $INTERFACE_F90
sed -i -e "s/SetScreenOn/setscreenon/g" $INTERFACE_F90
sed -i -e "s/SetSelectedOutputOn/setselectedoutputon/g" $INTERFACE_F90
sed -i -e "s/SetSpeciesSaveOn/setspeciessaveon/g" $INTERFACE_F90
sed -i -e "s/SetTemperature/settemperature/g" $INTERFACE_F90
sed -i -e "s/SetTimeConversion/settimeconversion/g" $INTERFACE_F90
sed -i -e "s/SetTimeStep/settimestep/g" $INTERFACE_F90
sed -i -e "s/SetTime/settime/g" $INTERFACE_F90
sed -i -e "s/SetUnitsExchange/setunitsexchange/g" $INTERFACE_F90
sed -i -e "s/SetUnitsGasPhase/setunitsgasphase/g" $INTERFACE_F90
sed -i -e "s/SetUnitsKinetics/setunitskinetics/g" $INTERFACE_F90
sed -i -e "s/SetUnitsPPassemblage/setunitsppassemblage/g" $INTERFACE_F90
sed -i -e "s/SetUnitsSolution/setunitssolution/g" $INTERFACE_F90
sed -i -e "s/SetUnitsSSassemblage/setunitsssassemblage/g" $INTERFACE_F90
sed -i -e "s/SetUnitsSSassemblage/setunitsssassemblage/g" $INTERFACE_F90
sed -i -e "s/SetUnitsSurface/setunitssurface/g" $INTERFACE_F90
sed -i -e "s/SpeciesConcentrations2Module/speciesconcentrations2module/g" $INTERFACE_F90
sed -i -e "s/UseSolutionDensityVolume/usesolutiondensityvolume/g" $INTERFACE_F90
sed -i -e "s/WarningMessage/warningmessage/g" $INTERFACE_F90
sed -i -e "s/GetSpeciesLog10Gammas/getspecieslog10gammas/g" $INTERFACE_F90
sed -i -e "s/GetExchangeSpeciesCount/getexchangespeciescount/g" $INTERFACE_F90
sed -i -e "s/GetExchangeSpeciesName/getexchangespeciesname/g" $INTERFACE_F90
sed -i -e "s/GetExchangeName/getexchangename/g" $INTERFACE_F90
sed -i -e "s/GetSurfaceSpeciesCount/getsurfacespeciescount/g" $INTERFACE_F90
sed -i -e "s/GetSurfaceSpeciesName/getsurfacespeciesname/g" $INTERFACE_F90
sed -i -e "s/GetSurfaceType/getsurfacetype/g" $INTERFACE_F90
sed -i -e "s/GetSurfaceName/getsurfacename/g" $INTERFACE_F90
sed -i -e "s/GetEquilibriumPhasesCount/getequilibriumphasescount/g" $INTERFACE_F90
sed -i -e "s/GetEquilibriumPhasesName/getequilibriumphasesname/g" $INTERFACE_F90
sed -i -e "s/GetGasComponentsCount/getgascomponentscount/g" $INTERFACE_F90
sed -i -e "s/GetGasComponentsName/getgascomponentsname/g" $INTERFACE_F90
sed -i -e "s/GetKineticReactionsCount/getkineticreactionscount/g" $INTERFACE_F90
sed -i -e "s/GetKineticReactionsName/getkineticreactionsname/g" $INTERFACE_F90
sed -i -e "s/GetSolidSolutionComponentsCount/getsolidsolutioncomponentscount/g" $INTERFACE_F90
sed -i -e "s/GetSolidSolutionComponentsName/getsolidsolutioncomponentsname/g" $INTERFACE_F90
sed -i -e "s/GetSolidSolutionName/getsolidsolutionname/g" $INTERFACE_F90
sed -i -e "s/GetSICount/getsicount/g" $INTERFACE_F90
sed -i -e "s/GetSIName/getsiname/g" $INTERFACE_F90
sed -i -e "s/StateSave/statesave/g" $INTERFACE_F90
sed -i -e "s/StateApply/stateapply/g" $INTERFACE_F90
sed -i -e "s/StateDelete/statedelete/g" $INTERFACE_F90
#sed -i -e "s/BMI_Finalize/bmi_finalize/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetComponentName/bmi_getcomponentname/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetCurrentTime/bmi_getcurrenttime/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetEndTime/bmi_getendtime/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetInputItemCount/bmi_getinputitemcount/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetInputVarNames/bmi_getinputvarnames/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetOutputItemCount/bmi_getoutputitemcount/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetOutputVarNames/bmi_getoutputvarnames/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetTimeStep/bmi_gettimestep/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetTimeUnits/bmi_gettimeunits/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetValue/bmi_getvalue/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetVarItemsize/bmi_getvaritemsize/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetVarNbytes/bmi_getvarnbytes/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetVarType/bmi_getvartype/g" $INTERFACE_F90
#sed -i -e "s/BMI_GetVarUnits/bmi_getvarunits/g" $INTERFACE_F90
#sed -i -e "s/BMI_Initialize/bmi_initialize/g" $INTERFACE_F90
#sed -i -e "s/BMI_SetValue/bmi_setvalue/g" $INTERFACE_F90
#sed -i -e "s/BMI_Update/bmi_update/g" $INTERFACE_F90
sed -i -e "s/GetComponents/getcomponents/g" $INTERFACE_F90
sed -i -e "s/GetGridCellCountYAML/getgridcellcountyaml/g" $INTERFACE_F90
sed -i -e "s/GetSelectedOutputHeadings/getselectedoutputheadings/g" $INTERFACE_F90
sed -i -e "s/GetTemperature/gettemperature/g" $INTERFACE_F90
sed -i -e "s/GetViscosity/getviscosity/g" $INTERFACE_F90
sed -i -e "s/GetIthConcentration/getithconcentration/g" $INTERFACE_F90
sed -i -e "s/GetIthSpeciesConcentration/getithspeciesconcentration/g" $INTERFACE_F90
sed -i -e "s/SetIthConcentration/setithconcentration/g" $INTERFACE_F90
sed -i -e "s/SetIthSpeciesConcentration/setithspeciesconcentration/g" $INTERFACE_F90
sed -i -e "s/InitialSolutions2Module/initialsolutions2module/g" $INTERFACE_F90
sed -i -e "s/InitialEquilibriumPhases2Module/initialequilibriumphases2module/g" $INTERFACE_F90
sed -i -e "s/InitialExchanges2Module/initialexchanges2module/g" $INTERFACE_F90
sed -i -e "s/InitialSurfaces2Module/initialsurfaces2module/g" $INTERFACE_F90
sed -i -e "s/InitialGasPhases2Module/initialgasphases2module/g" $INTERFACE_F90
sed -i -e "s/InitialSolidSolutions2Module/initialsolidsolutions2module/g" $INTERFACE_F90
sed -i -e "s/InitialKinetics2Module/initialkinetics2module/g" $INTERFACE_F90
sed -i -e "s/DestroyYAMLPhreeqcRM/destroyyamlphreeqcrm/g" $YAML_INTERFACE_F90
sed -i -e "s/CreateYAMLPhreeqcRM/createyamlphreeqcrm/g" $YAML_INTERFACE_F90
sed -i -e "s/WriteYAMLDoc/writeyamldoc/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLAddOutputVars/yamladdoutputvars/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLClear/yamlclear/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLCloseFiles/yamlclosefiles/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLCreateMapping/yamlcreatemapping/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLDumpModule/yamldumpmodule/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLFindComponents/yamlfindcomponents/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialSolutions2Module/yamlinitialsolutions2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialEquilibriumPhases2Module/yamlinitialequilibriumphases2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialExchanges2Module/yamlinitialexchanges2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialSurfaces2Module/yamlinitialsurfaces2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialGasPhases2Module/yamlinitialgasphases2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialSolidSolutions2Module/yamlinitialsolidsolutions2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialKinetics2Module/yamlinitialkinetics2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialPhreeqc2Module/yamlinitialphreeqc2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialPhreeqc2Module_mix/yamlinitialphreeqc2module_mix/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLInitialPhreeqcCell2Module/yamlinitialphreeqccell2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLLoadDatabase/yamlloaddatabase/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLLogMessage/yamllogmessage/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLOpenFiles/yamlopenfiles/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLOutputMessage/yamloutputmessage/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLRunCells/yamlruncells/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLRunFile/yamlrunfile/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLRunString/yamlrunstring/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLScreenMessage/yamlscreenmessage/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetComponentH2O/yamlsetcomponenth2o/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetConcentrations/yamlsetconcentrations/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetCurrentSelectedOutputUserNumber/yamlsetcurrentselectedoutputusernumber/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetDensityUser/yamlsetdensityuser/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetDumpFileName/yamlsetdumpfilename/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetErrorHandlerMode/yamlseterrorhandlermode/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetErrorOn/yamlseterroron/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetFilePrefix/yamlsetfileprefix/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetGasCompMoles/yamlsetgascompmoles/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetGasPhaseVolume/yamlsetgasphasevolume/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetGridCellCount/yamlsetgridcellcount/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetNthSelectedOutput/yamlsetnthselectedoutput/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetPartitionUZSolids/yamlsetpartitionuzsolids/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetPorosity/yamlsetporosity/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetPressure/yamlsetpressure/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetPrintChemistryMask/yamlsetprintchemistrymask/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetPrintChemistryOn/yamlsetprintchemistryon/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetRebalanceByCell/yamlsetrebalancebycell/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetRebalanceFraction/yamlsetrebalancefraction/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetRepresentativeVolume/yamlsetrepresentativevolume/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetSaturationUser/yamlsetsaturationuser/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetScreenOn/yamlsetscreenon/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetSelectedOutputOn/yamlsetselectedoutputon/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetSpeciesSaveOn/yamlsetspeciessaveon/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetTemperature/yamlsettemperature/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetTimeConversion/yamlsettimeconversion/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetTimeStep/yamlsettimestep/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetTime/yamlsettime/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsExchange/yamlsetunitsexchange/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsGasPhase/yamlsetunitsgasphase/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsKinetics/yamlsetunitskinetics/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsPPassemblage/yamlsetunitsppassemblage/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsSolution/yamlsetunitssolution/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsSSassemblage/yamlsetunitsssassemblage/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSetUnitsSurface/yamlsetunitssurface/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLSpeciesConcentrations2Module/yamlspeciesconcentrations2module/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLStateSave/yamlstatesave/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLStateApply/yamlstateapply/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLStateDelete/yamlstatedelete/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLThreadCount/yamlthreadcount/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLUseSolutionDensityVolume/yamlusesolutiondensityvolume/g" $YAML_INTERFACE_F90
sed -i -e "s/YAMLWarningMessage/yamlwarningmessage/g" $YAML_INTERFACE_F90