#!/bin/sh
export RM_INTERFACE_F90=../src/RM_interface.F90
export YAML_INTERFACE_F90=../src/YAML_interface.F90
export BMI_INTERFACE_F90=../src/BMI_interface.F90
# sed -i -e "s/PhreeqcRM/phreeqcrm/g" $RM_INTERFACE_F90
sed -i -e "s/GetGridCellCountYAML/getgridcellcountyaml/g" $RM_INTERFACE_F90
sed -i -e "s/SetGridCellCountYAML/setgridcellcountyaml/g" | \
sed -i -e "s/RM_Abort/rm_abort/g" | \
sed -i -e "s/RM_CloseFiles/rm_closefiles/g" | \
sed -i -e "s/RM_Concentrations2Utility/rm_concentrations2utility/g" | \
sed -i -e "s/RM_CreateMapping/rm_createmapping/g" | \
sed -i -e "s/RM_Create/rm_create/g" | \
sed -i -e "s/RM_DecodeError/rm_decodeerror/g" | \
sed -i -e "s/RM_Destroy/rm_destroy/g" | \
sed -i -e "s/RM_DumpModule/rm_dumpmodule/g" | \
sed -i -e "s/RM_ErrorMessage/rm_errormessage/g" | \
sed -i -e "s/RM_FindComponents/rm_findcomponents/g" | \
sed -i -e "s/RM_GetBackwardMapping/rm_getbackwardmapping/g" | \
sed -i -e "s/RM_GetChemistryCellCount/rm_getchemistrycellcount/g" | \
sed -i -e "s/RM_GetComponentCount/rm_getcomponentcount/g" | \
sed -i -e "s/RM_GetComponent/rm_getcomponent/g" | \
sed -i -e "s/RM_GetConcentrations/rm_getconcentrations/g" | \
sed -i -e "s/RM_GetCurrentSelectedOutputUserNumber/rm_getcurrentselectedoutputusernumber/g" | \
sed -i -e "s/RM_GetDensityCalculated/rm_getdensitycalculated/g" | \
sed -i -e "s/RM_GetDensity/rm_getdensity/g" | \
sed -i -e "s/RM_GetEndCell/rm_getendcell/g" | \
sed -i -e "s/RM_GetErrorString/rm_geterrorstring/g" | \
sed -i -e "s/RM_GetErrorStringLength/rm_geterrorstringlength/g" | \
sed -i -e "s/RM_GetFilePrefix/rm_getfileprefix/g" | \
sed -i -e "s/RM_GetGasCompMoles/rm_getgascompmoles/g" | \
sed -i -e "s/RM_GetGasCompPhi/rm_getgascompphi/g" | \
sed -i -e "s/RM_GetGasCompPressures/rm_getgascomppressures/g" | \
sed -i -e "s/RM_GetGasPhaseVolume/rm_getgasphasevolume/g" | \
sed -i -e "s/RM_GetGfw/rm_getgfw/g" | \
sed -i -e "s/RM_GetGridCellCount/rm_getgridcellcount/g" | \
sed -i -e "s/RM_GetIPhreeqcId/rm_getiphreeqcid/g" | \
sed -i -e "s/RM_GetMpiMyself/rm_getmpimyself/g" | \
sed -i -e "s/RM_GetMpiTasks/rm_getmpitasks/g" | \
sed -i -e "s/RM_GetNthSelectedOutputUserNumber/rm_getnthselectedoutputusernumber/g" | \
sed -i -e "s/RM_GetPorosity/rm_getporosity/g" | \
sed -i -e "s/RM_GetPressure/rm_getpressure/g" | \
sed -i -e "s/RM_GetSaturationCalculated/rm_getsaturationcalculated/g" | \
sed -i -e "s/RM_GetSaturation/rm_getsaturation/g" | \
sed -i -e "s/RM_GetSelectedOutputColumnCount/rm_getselectedoutputcolumncount/g" | \
sed -i -e "s/RM_GetSelectedOutputCount/rm_getselectedoutputcount/g" | \
sed -i -e "s/RM_GetSelectedOutputHeading/rm_getselectedoutputheading/g" | \
sed -i -e "s/RM_GetSelectedOutputRowCount/rm_getselectedoutputrowcount/g" | \
sed -i -e "s/RM_GetSelectedOutput/rm_getselectedoutput/g" | \
sed -i -e "s/RM_GetSolutionVolume/rm_getsolutionvolume/g" | \
sed -i -e "s/RM_GetSpeciesConcentrations/rm_getspeciesconcentrations/g" | \
sed -i -e "s/RM_GetSpeciesCount/rm_getspeciescount/g" | \
sed -i -e "s/RM_GetSpeciesD25/rm_getspeciesd25/g" | \
sed -i -e "s/RM_GetSpeciesLog10Molalities/rm_getspecieslog10molalities/g" | \
sed -i -e "s/RM_GetSpeciesName/rm_getspeciesname/g" | \
sed -i -e "s/RM_GetSpeciesSaveOn/rm_getspeciessaveon/g" | \
sed -i -e "s/RM_GetSpeciesZ/rm_getspeciesz/g" | \
sed -i -e "s/RM_GetStartCell/rm_getstartcell/g" | \
sed -i -e "s/RM_GetThreadCount/rm_getthreadcount/g" | \
sed -i -e "s/RM_GetTimeConversion/rm_gettimeconversion/g" | \
sed -i -e "s/RM_GetTimeStep/rm_gettimestep/g" | \
sed -i -e "s/RM_GetTime/rm_gettime/g" | \
sed -i -e "s/RM_InitializeYAML/rm_initializeyaml/g" | \
sed -i -e "s/RM_InitialPhreeqc2Concentrations/rm_initialphreeqc2concentrations/g" | \
sed -i -e "s/RM_InitialPhreeqc2Module/rm_initialphreeqc2module/g" | \
sed -i -e "s/RM_InitialPhreeqcCell2Module/rm_initialphreeqccell2module/g" | \
sed -i -e "s/RM_InitialPhreeqc2SpeciesConcentrations/rm_initialphreeqc2speciesconcentrations/g" | \
sed -i -e "s/RM_LoadDatabase/rm_loaddatabase/g" | \
sed -i -e "s/RM_LogMessage/rm_logmessage/g" | \
sed -i -e "s/RM_MpiWorkerBreak/rm_mpiworkerbreak/g" | \
sed -i -e "s/RM_MpiWorker/rm_mpiworker/g" | \
sed -i -e "s/RM_OpenFiles/rm_openfiles/g" | \
sed -i -e "s/RM_OutputMessage/rm_outputmessage/g" | \
sed -i -e "s/RM_RunCells/rm_runcells/g" | \
sed -i -e "s/RM_RunFile/rm_runfile/g" | \
sed -i -e "s/RM_RunString/rm_runstring/g" | \
sed -i -e "s/RM_ScreenMessage/rm_screenmessage/g" | \
sed -i -e "s/RM_SetComponentH2O/rm_setcomponenth2o/g" | \
sed -i -e "s/RM_SetConcentrations/rm_setconcentrations/g" | \
sed -i -e "s/RM_SetCurrentSelectedOutputUserNumber/rm_setcurrentselectedoutputusernumber/g" | \
sed -i -e "s/RM_SetDensityUser/rm_setdensityuser/g" | \
sed -i -e "s/RM_SetDensity/rm_setdensity/g" | \
sed -i -e "s/RM_SetDumpFileName/rm_setdumpfilename/g" | \
sed -i -e "s/RM_SetErrorHandlerMode/rm_seterrorhandlermode/g" | \
sed -i -e "s/RM_SetErrorOn/rm_seterroron/g" | \
sed -i -e "s/RM_SetFilePrefix/rm_setfileprefix/g" | \
sed -i -e "s/RM_SetGasCompMoles/rm_setgascompmoles/g" | \
sed -i -e "s/RM_SetGasPhaseVolume/rm_setgasphasevolume/g" | \
sed -i -e "s/RM_SetMpiWorkerCallback/rm_setmpiworkercallback/g" | \
sed -i -e "s/RM_SetNthSelectedOutput/rm_setnthselectedoutput/g" | \
sed -i -e "s/RM_SetPartitionUZSolids/rm_setpartitionuzsolids/g" | \
sed -i -e "s/RM_SetPorosity/rm_setporosity/g" | \
sed -i -e "s/RM_SetPrintChemistryMask/rm_setprintchemistrymask/g" | \
sed -i -e "s/RM_SetPrintChemistryOn/rm_setprintchemistryon/g" | \
sed -i -e "s/RM_SetPressure/rm_setpressure/g" | \
sed -i -e "s/RM_SetRebalanceFraction/rm_setrebalancefraction/g" | \
sed -i -e "s/RM_SetRebalanceByCell/rm_setrebalancebycell/g" | \
sed -i -e "s/RM_SetRepresentativeVolume/rm_setrepresentativevolume/g" | \
sed -i -e "s/RM_SetSaturationUser/rm_setsaturationuser/g" | \
sed -i -e "s/RM_SetSaturation/rm_setsaturation/g" | \
sed -i -e "s/RM_SetScreenOn/rm_setscreenon/g" | \
sed -i -e "s/RM_SetSelectedOutputOn/rm_setselectedoutputon/g" | \
sed -i -e "s/RM_SetSpeciesSaveOn/rm_setspeciessaveon/g" | \
sed -i -e "s/RM_SetTemperature/rm_settemperature/g" | \
sed -i -e "s/RM_SetTimeConversion/rm_settimeconversion/g" | \
sed -i -e "s/RM_SetTimeStep/rm_settimestep/g" | \
sed -i -e "s/RM_SetTime/rm_settime/g" | \
sed -i -e "s/RM_SetUnitsExchange/rm_setunitsexchange/g" | \
sed -i -e "s/RM_SetUnitsGasPhase/rm_setunitsgasphase/g" | \
sed -i -e "s/RM_SetUnitsKinetics/rm_setunitskinetics/g" | \
sed -i -e "s/RM_SetUnitsPPassemblage/rm_setunitsppassemblage/g" | \
sed -i -e "s/RM_SetUnitsSolution/rm_setunitssolution/g" | \
sed -i -e "s/RM_SetUnitsSSassemblage/rm_setunitsssassemblage/g" | \
sed -i -e "s/RM_SetUnitsSSassemblage/rm_setunitsssassemblage/g" | \
sed -i -e "s/RM_SetUnitsSurface/rm_setunitssurface/g" | \
sed -i -e "s/RM_SpeciesConcentrations2Module/rm_speciesconcentrations2module/g" | \
sed -i -e "s/RM_UseSolutionDensityVolume/rm_usesolutiondensityvolume/g" | \
sed -i -e "s/RM_WarningMessage/rm_warningmessage/g" | \
sed -i -e "s/RM_GetSpeciesLog10Gammas/rm_getspecieslog10gammas/g" | \
sed -i -e "s/RM_GetExchangeSpeciesCount/rm_getexchangespeciescount/g" | \
sed -i -e "s/RM_GetExchangeSpeciesName/rm_getexchangespeciesname/g" | \
sed -i -e "s/RM_GetExchangeName/rm_getexchangename/g" | \
sed -i -e "s/RM_GetSurfaceSpeciesCount/rm_getsurfacespeciescount/g" | \
sed -i -e "s/RM_GetSurfaceSpeciesName/rm_getsurfacespeciesname/g" | \
sed -i -e "s/RM_GetSurfaceType/rm_getsurfacetype/g" | \
sed -i -e "s/RM_GetSurfaceName/rm_getsurfacename/g" | \
sed -i -e "s/RM_GetEquilibriumPhasesCount/rm_getequilibriumphasescount/g" | \
sed -i -e "s/RM_GetEquilibriumPhasesName/rm_getequilibriumphasesname/g" | \
sed -i -e "s/RM_GetGasComponentsCount/rm_getgascomponentscount/g" | \
sed -i -e "s/RM_GetGasComponentsName/rm_getgascomponentsname/g" | \
sed -i -e "s/RM_GetKineticReactionsCount/rm_getkineticreactionscount/g" | \
sed -i -e "s/RM_GetKineticReactionsName/rm_getkineticreactionsname/g" | \
sed -i -e "s/RM_GetSolidSolutionComponentsCount/rm_getsolidsolutioncomponentscount/g" | \
sed -i -e "s/RM_GetSolidSolutionComponentsName/rm_getsolidsolutioncomponentsname/g" | \
sed -i -e "s/RM_GetSolidSolutionName/rm_getsolidsolutionname/g" | \
sed -i -e "s/RM_GetSICount/rm_getsicount/g" | \
sed -i -e "s/RM_GetSIName/rm_getsiname/g" | \
sed -i -e "s/RM_StateSave/rm_statesave/g" | \
sed -i -e "s/RM_StateApply/rm_stateapply/g" | \
sed -i -e "s/RM_StateDelete/rm_statedelete/g" | \
sed -i -e "s/RM_GetComponents/rm_getcomponents/g" | \
sed -i -e "s/RM_GetGridCellCountYAML/rm_getgridcellcountyaml/g" | \
sed -i -e "s/RM_GetSelectedOutputHeadings/rm_getselectedoutputheadings/g" | \
sed -i -e "s/RM_GetTemperature/rm_gettemperature/g" | \
sed -i -e "s/RM_GetViscosity/rm_getviscosity/g" | \
sed -i -e "s/RM_GetIthConcentration/rm_getithconcentration/g" | \
sed -i -e "s/RM_GetIthSpeciesConcentration/rm_getithspeciesconcentration/g" | \
sed -i -e "s/RM_SetIthConcentration/rm_setithconcentration/g" | \
sed -i -e "s/RM_SetIthSpeciesConcentration/rm_setithspeciesconcentration/g" | \
sed -i -e "s/RM_InitialSolutions2Module/rm_initialsolutions2module/g" | \
sed -i -e "s/RM_InitialEquilibriumPhases2Module/rm_initialequilibriumphases2module/g" | \
sed -i -e "s/RM_InitialExchanges2Module/rm_initialexchanges2module/g" | \
sed -i -e "s/RM_InitialSurfaces2Module/rm_initialsurfaces2module/g" | \
sed -i -e "s/RM_InitialGasPhases2Module/rm_initialgasphases2module/g" | \
sed -i -e "s/RM_InitialSolidSolutions2Module/rm_initialsolidsolutions2module/g" | \
sed -i -e "s/RM_InitialKinetics2Module/rm_initialkinetics2module/g" 
sed -i -e "s/DestroyYAMLPhreeqcRM/destroyyamlphreeqcrm/g" $YAML_INTERFACE_F90
sed -i -e "s/CreateYAMLPhreeqcRM/createyamlphreeqcrm/g" | \
sed -i -e "s/WriteYAMLDoc/writeyamldoc/g" | \
sed -i -e "s/YAMLAddOutputVars/yamladdoutputvars/g" | \
sed -i -e "s/YAMLClear/yamlclear/g" | \
sed -i -e "s/YAMLCloseFiles/yamlclosefiles/g" | \
sed -i -e "s/YAMLCreateMapping/yamlcreatemapping/g" | \
sed -i -e "s/YAMLDumpModule/yamldumpmodule/g" | \
sed -i -e "s/YAMLFindComponents/yamlfindcomponents/g" | \
sed -i -e "s/YAMLInitialSolutions2Module/yamlinitialsolutions2module/g" | \
sed -i -e "s/YAMLInitialEquilibriumPhases2Module/yamlinitialequilibriumphases2module/g" | \
sed -i -e "s/YAMLInitialExchanges2Module/yamlinitialexchanges2module/g" | \
sed -i -e "s/YAMLInitialSurfaces2Module/yamlinitialsurfaces2module/g" | \
sed -i -e "s/YAMLInitialGasPhases2Module/yamlinitialgasphases2module/g" | \
sed -i -e "s/YAMLInitialSolidSolutions2Module/yamlinitialsolidsolutions2module/g" | \
sed -i -e "s/YAMLInitialKinetics2Module/yamlinitialkinetics2module/g" | \
sed -i -e "s/YAMLInitialPhreeqc2Module/yamlinitialphreeqc2module/g" | \
sed -i -e "s/YAMLInitialPhreeqc2Module_mix/yamlinitialphreeqc2module_mix/g" | \
sed -i -e "s/YAMLInitialPhreeqcCell2Module/yamlinitialphreeqccell2module/g" | \
sed -i -e "s/YAMLLoadDatabase/yamlloaddatabase/g" | \
sed -i -e "s/YAMLLogMessage/yamllogmessage/g" | \
sed -i -e "s/YAMLOpenFiles/yamlopenfiles/g" | \
sed -i -e "s/YAMLOutputMessage/yamloutputmessage/g" | \
sed -i -e "s/YAMLRunCells/yamlruncells/g" | \
sed -i -e "s/YAMLRunFile/yamlrunfile/g" | \
sed -i -e "s/YAMLRunString/yamlrunstring/g" | \
sed -i -e "s/YAMLScreenMessage/yamlscreenmessage/g" | \
sed -i -e "s/YAMLSetComponentH2O/yamlsetcomponenth2o/g" | \
sed -i -e "s/YAMLSetConcentrations/yamlsetconcentrations/g" | \
sed -i -e "s/YAMLSetCurrentSelectedOutputUserNumber/yamlsetcurrentselectedoutputusernumber/g" | \
sed -i -e "s/YAMLSetDensityUser/yamlsetdensityuser/g" | \
sed -i -e "s/YAMLSetDumpFileName/yamlsetdumpfilename/g" | \
sed -i -e "s/YAMLSetErrorHandlerMode/yamlseterrorhandlermode/g" | \
sed -i -e "s/YAMLSetErrorOn/yamlseterroron/g" | \
sed -i -e "s/YAMLSetFilePrefix/yamlsetfileprefix/g" | \
sed -i -e "s/YAMLSetGasCompMoles/yamlsetgascompmoles/g" | \
sed -i -e "s/YAMLSetGasPhaseVolume/yamlsetgasphasevolume/g" | \
sed -i -e "s/YAMLSetGridCellCount/yamlsetgridcellcount/g" | \
sed -i -e "s/YAMLSetNthSelectedOutput/yamlsetnthselectedoutput/g" | \
sed -i -e "s/YAMLSetPartitionUZSolids/yamlsetpartitionuzsolids/g" | \
sed -i -e "s/YAMLSetPorosity/yamlsetporosity/g" | \
sed -i -e "s/YAMLSetPressure/yamlsetpressure/g" | \
sed -i -e "s/YAMLSetPrintChemistryMask/yamlsetprintchemistrymask/g" | \
sed -i -e "s/YAMLSetPrintChemistryOn/yamlsetprintchemistryon/g" | \
sed -i -e "s/YAMLSetRebalanceByCell/yamlsetrebalancebycell/g" | \
sed -i -e "s/YAMLSetRebalanceFraction/yamlsetrebalancefraction/g" | \
sed -i -e "s/YAMLSetRepresentativeVolume/yamlsetrepresentativevolume/g" | \
sed -i -e "s/YAMLSetSaturationUser/yamlsetsaturationuser/g" | \
sed -i -e "s/YAMLSetScreenOn/yamlsetscreenon/g" | \
sed -i -e "s/YAMLSetSelectedOutputOn/yamlsetselectedoutputon/g" | \
sed -i -e "s/YAMLSetSpeciesSaveOn/yamlsetspeciessaveon/g" | \
sed -i -e "s/YAMLSetTemperature/yamlsettemperature/g" | \
sed -i -e "s/YAMLSetTimeConversion/yamlsettimeconversion/g" | \
sed -i -e "s/YAMLSetTimeStep/yamlsettimestep/g" | \
sed -i -e "s/YAMLSetTime/yamlsettime/g" | \
sed -i -e "s/YAMLSetUnitsExchange/yamlsetunitsexchange/g" | \
sed -i -e "s/YAMLSetUnitsGasPhase/yamlsetunitsgasphase/g" | \
sed -i -e "s/YAMLSetUnitsKinetics/yamlsetunitskinetics/g" | \
sed -i -e "s/YAMLSetUnitsPPassemblage/yamlsetunitsppassemblage/g" | \
sed -i -e "s/YAMLSetUnitsSolution/yamlsetunitssolution/g" | \
sed -i -e "s/YAMLSetUnitsSSassemblage/yamlsetunitsssassemblage/g" | \
sed -i -e "s/YAMLSetUnitsSurface/yamlsetunitssurface/g" | \
sed -i -e "s/YAMLSpeciesConcentrations2Module/yamlspeciesconcentrations2module/g" | \
sed -i -e "s/YAMLStateSave/yamlstatesave/g" | \
sed -i -e "s/YAMLStateApply/yamlstateapply/g" | \
sed -i -e "s/YAMLStateDelete/yamlstatedelete/g" | \
sed -i -e "s/YAMLThreadCount/yamlthreadcount/g" | \
sed -i -e "s/YAMLUseSolutionDensityVolume/yamlusesolutiondensityvolume/g" | \
sed -i -e "s/YAMLWarningMessage/yamlwarningmessage/g" 
sed -i -e "s/Abort/abort/g" $BMI_INTERFACE_F90
sed -i -e "s/CloseFiles/closefiles/g" | \
sed -i -e "s/Concentrations2Utility/concentrations2utility/g" | \
sed -i -e "s/CreateMapping/createmapping/g" | \
sed -i -e "s/Create/create/g" | \
sed -i -e "s/DecodeError/decodeerror/g" | \
sed -i -e "s/Destroy/destroy/g" | \
sed -i -e "s/DumpModule/dumpmodule/g" | \
sed -i -e "s/ErrorMessage/errormessage/g" | \
sed -i -e "s/FindComponents/findcomponents/g" | \
sed -i -e "s/GetBackwardMapping/getbackwardmapping/g" | \
sed -i -e "s/GetChemistryCellCount/getchemistrycellcount/g" | \
sed -i -e "s/GetComponentCount/getcomponentcount/g" | \
sed -i -e "s/GetComponent/getcomponent/g" | \
sed -i -e "s/GetConcentrations/getconcentrations/g" | \
sed -i -e "s/GetCurrentSelectedOutputUserNumber/getcurrentselectedoutputusernumber/g" | \
sed -i -e "s/GetDensityCalculated/getdensitycalculated/g" | \
sed -i -e "s/GetDensity/getdensity/g" | \
sed -i -e "s/GetEndCell/getendcell/g" | \
sed -i -e "s/GetErrorString/geterrorstring/g" | \
sed -i -e "s/GetErrorStringLength/geterrorstringlength/g" | \
sed -i -e "s/GetFilePrefix/getfileprefix/g" | \
sed -i -e "s/GetGasCompMoles/getgascompmoles/g" | \
sed -i -e "s/GetGasCompPhi/getgascompphi/g" | \
sed -i -e "s/GetGasCompPressures/getgascomppressures/g" | \
sed -i -e "s/GetGasPhaseVolume/getgasphasevolume/g" | \
sed -i -e "s/GetGfw/getgfw/g" | \
sed -i -e "s/GetGridCellCount/getgridcellcount/g" | \
sed -i -e "s/GetIPhreeqcId/getiphreeqcid/g" | \
sed -i -e "s/GetMpiMyself/getmpimyself/g" | \
sed -i -e "s/GetMpiTasks/getmpitasks/g" | \
sed -i -e "s/GetNthSelectedOutputUserNumber/getnthselectedoutputusernumber/g" | \
sed -i -e "s/GetPorosity/getporosity/g" | \
sed -i -e "s/GetPressure/getpressure/g" | \
sed -i -e "s/GetSaturationCalculated/getsaturationcalculated/g" | \
sed -i -e "s/GetSaturation/getsaturation/g" | \
sed -i -e "s/GetSelectedOutputColumnCount/getselectedoutputcolumncount/g" | \
sed -i -e "s/GetSelectedOutputCount/getselectedoutputcount/g" | \
sed -i -e "s/GetSelectedOutputHeading/getselectedoutputheading/g" | \
sed -i -e "s/GetSelectedOutputRowCount/getselectedoutputrowcount/g" | \
sed -i -e "s/GetSelectedOutput/getselectedoutput/g" | \
sed -i -e "s/GetSolutionVolume/getsolutionvolume/g" | \
sed -i -e "s/GetSpeciesConcentrations/getspeciesconcentrations/g" | \
sed -i -e "s/GetSpeciesCount/getspeciescount/g" | \
sed -i -e "s/GetSpeciesD25/getspeciesd25/g" | \
sed -i -e "s/GetSpeciesLog10Molalities/getspecieslog10molalities/g" | \
sed -i -e "s/GetSpeciesName/getspeciesname/g" | \
sed -i -e "s/GetSpeciesSaveOn/getspeciessaveon/g" | \
sed -i -e "s/GetSpeciesZ/getspeciesz/g" | \
sed -i -e "s/GetStartCell/getstartcell/g" | \
sed -i -e "s/GetThreadCount/getthreadcount/g" | \
sed -i -e "s/GetTimeConversion/gettimeconversion/g" | \
sed -i -e "s/GetTimeStep/gettimestep/g" | \
sed -i -e "s/GetTime/gettime/g" | \
sed -i -e "s/InitializeYAML/initializeyaml/g" | \
sed -i -e "s/InitialPhreeqc2Concentrations/initialphreeqc2concentrations/g" | \
sed -i -e "s/InitialPhreeqc2Module/initialphreeqc2module/g" | \
sed -i -e "s/InitialPhreeqcCell2Module/initialphreeqccell2module/g" | \
sed -i -e "s/InitialPhreeqc2SpeciesConcentrations/initialphreeqc2speciesconcentrations/g" | \
sed -i -e "s/LoadDatabase/loaddatabase/g" | \
sed -i -e "s/LogMessage/logmessage/g" | \
sed -i -e "s/MpiWorkerBreak/mpiworkerbreak/g" | \
sed -i -e "s/MpiWorker/mpiworker/g" | \
sed -i -e "s/OpenFiles/openfiles/g" | \
sed -i -e "s/OutputMessage/outputmessage/g" | \
sed -i -e "s/RunCells/runcells/g" | \
sed -i -e "s/RunFile/runfile/g" | \
sed -i -e "s/RunString/runstring/g" | \
sed -i -e "s/ScreenMessage/screenmessage/g" | \
sed -i -e "s/SetComponentH2O/setcomponenth2o/g" | \
sed -i -e "s/SetConcentrations/setconcentrations/g" | \
sed -i -e "s/SetCurrentSelectedOutputUserNumber/setcurrentselectedoutputusernumber/g" | \
sed -i -e "s/SetDensityUser/setdensityuser/g" | \
sed -i -e "s/SetDensity/setdensity/g" | \
sed -i -e "s/SetDumpFileName/setdumpfilename/g" | \
sed -i -e "s/SetErrorHandlerMode/seterrorhandlermode/g" | \
sed -i -e "s/SetErrorOn/seterroron/g" | \
sed -i -e "s/SetFilePrefix/setfileprefix/g" | \
sed -i -e "s/SetGasCompMoles/setgascompmoles/g" | \
sed -i -e "s/SetGasPhaseVolume/setgasphasevolume/g" | \
sed -i -e "s/SetMpiWorkerCallback/setmpiworkercallback/g" | \
sed -i -e "s/SetNthSelectedOutput/setnthselectedoutput/g" | \
sed -i -e "s/SetPartitionUZSolids/setpartitionuzsolids/g" | \
sed -i -e "s/SetPorosity/setporosity/g" | \
sed -i -e "s/SetPrintChemistryMask/setprintchemistrymask/g" | \
sed -i -e "s/SetPrintChemistryOn/setprintchemistryon/g" | \
sed -i -e "s/SetPressure/setpressure/g" | \
sed -i -e "s/SetRebalanceFraction/setrebalancefraction/g" | \
sed -i -e "s/SetRebalanceByCell/setrebalancebycell/g" | \
sed -i -e "s/SetRepresentativeVolume/setrepresentativevolume/g" | \
sed -i -e "s/SetSaturationUser/setsaturationuser/g" | \
sed -i -e "s/SetSaturation/setsaturation/g" | \
sed -i -e "s/SetScreenOn/setscreenon/g" | \
sed -i -e "s/SetSelectedOutputOn/setselectedoutputon/g" | \
sed -i -e "s/SetSpeciesSaveOn/setspeciessaveon/g" | \
sed -i -e "s/SetTemperature/settemperature/g" | \
sed -i -e "s/SetTimeConversion/settimeconversion/g" | \
sed -i -e "s/SetTimeStep/settimestep/g" | \
sed -i -e "s/SetTime/settime/g" | \
sed -i -e "s/SetUnitsExchange/setunitsexchange/g" | \
sed -i -e "s/SetUnitsGasPhase/setunitsgasphase/g" | \
sed -i -e "s/SetUnitsKinetics/setunitskinetics/g" | \
sed -i -e "s/SetUnitsPPassemblage/setunitsppassemblage/g" | \
sed -i -e "s/SetUnitsSolution/setunitssolution/g" | \
sed -i -e "s/SetUnitsSSassemblage/setunitsssassemblage/g" | \
sed -i -e "s/SetUnitsSSassemblage/setunitsssassemblage/g" | \
sed -i -e "s/SetUnitsSurface/setunitssurface/g" | \
sed -i -e "s/SpeciesConcentrations2Module/speciesconcentrations2module/g" | \
sed -i -e "s/UseSolutionDensityVolume/usesolutiondensityvolume/g" | \
sed -i -e "s/WarningMessage/warningmessage/g" | \
sed -i -e "s/GetSpeciesLog10Gammas/getspecieslog10gammas/g" | \
sed -i -e "s/GetExchangeSpeciesCount/getexchangespeciescount/g" | \
sed -i -e "s/GetExchangeSpeciesName/getexchangespeciesname/g" | \
sed -i -e "s/GetExchangeName/getexchangename/g" | \
sed -i -e "s/GetSurfaceSpeciesCount/getsurfacespeciescount/g" | \
sed -i -e "s/GetSurfaceSpeciesName/getsurfacespeciesname/g" | \
sed -i -e "s/GetSurfaceType/getsurfacetype/g" | \
sed -i -e "s/GetSurfaceName/getsurfacename/g" | \
sed -i -e "s/GetEquilibriumPhasesCount/getequilibriumphasescount/g" | \
sed -i -e "s/GetEquilibriumPhasesName/getequilibriumphasesname/g" | \
sed -i -e "s/GetGasComponentsCount/getgascomponentscount/g" | \
sed -i -e "s/GetGasComponentsName/getgascomponentsname/g" | \
sed -i -e "s/GetKineticReactionsCount/getkineticreactionscount/g" | \
sed -i -e "s/GetKineticReactionsName/getkineticreactionsname/g" | \
sed -i -e "s/GetSolidSolutionComponentsCount/getsolidsolutioncomponentscount/g" | \
sed -i -e "s/GetSolidSolutionComponentsName/getsolidsolutioncomponentsname/g" | \
sed -i -e "s/GetSolidSolutionName/getsolidsolutionname/g" | \
sed -i -e "s/GetSICount/getsicount/g" | \
sed -i -e "s/GetSIName/getsiname/g" | \
sed -i -e "s/StateSave/statesave/g" | \
sed -i -e "s/StateApply/stateapply/g" | \
sed -i -e "s/StateDelete/statedelete/g" | \
sed -i -e "s/GetComponents/getcomponents/g" | \
sed -i -e "s/GetGridCellCountYAML/getgridcellcountyaml/g" | \
sed -i -e "s/GetSelectedOutputHeadings/getselectedoutputheadings/g" | \
sed -i -e "s/GetTemperature/gettemperature/g" | \
sed -i -e "s/GetViscosity/getviscosity/g" | \
sed -i -e "s/GetIthConcentration/getithconcentration/g" | \
sed -i -e "s/GetIthSpeciesConcentration/getithspeciesconcentration/g" | \
sed -i -e "s/SetIthConcentration/setithconcentration/g" | \
sed -i -e "s/SetIthSpeciesConcentration/setithspeciesconcentration/g" | \
sed -i -e "s/InitialSolutions2Module/initialsolutions2module/g" | \
sed -i -e "s/InitialEquilibriumPhases2Module/initialequilibriumphases2module/g" | \
sed -i -e "s/InitialExchanges2Module/initialexchanges2module/g" | \
sed -i -e "s/InitialSurfaces2Module/initialsurfaces2module/g" | \
sed -i -e "s/InitialGasPhases2Module/initialgasphases2module/g" | \
sed -i -e "s/InitialSolidSolutions2Module/initialsolidsolutions2module/g" | \
sed -i -e "s/InitialKinetics2Module/initialkinetics2module/g" 